package fastshare;

import java.io.File;

/**
 * Specifies shared resource (file)
 */
public class Resource {

    /**
     * Resource's location
     */
    private String location;
    /**
     * Resource's unique context (part of resource's URL)
     */
    private String resContext;
    
    /**
     * Sets location of resource
     * @param _location file's path
     */
    private void setLocation(String _location) {
        this.location = _location;
    }

    /**
     * Sets resource's context
     * @param _resContext resource's context (generated by RandomString)
     */
    private void setResContext(String _resContext) {
        this.resContext = _resContext;
    }

    /**
     * Returns resource's location
     * @return resource's location
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Returns resource's context
     * @return resource's context
     */
    public String getResContext() {
        return this.resContext;
    }

    /**
     * Constructor
     * @param _path file's path
     * @param _context resoure's context
     */
    public Resource(String _path, String _context) {
        File file = new File(_path);
        setLocation(file.getAbsolutePath());
        setResContext(_context + "/" + file.getName()); //file.getPath();
        resContext = resContext.replace("\\", "/");
    }

    /**
     * Generates URL of resource
     * @return URL of resource
     */
    public String getLink() {
        String ret = "";
        String ip = Settings.getIP();
        String port = Settings.getPort();

        ret = "http://"+ip+":"+port+"/shares"+resContext;
        
        return ret;
    }
}
